"""Catalogue entries for introductory and existing-situation chapters."""

from ema.audit.catalogue_types import AuditFact, Section, fact, section

GENERAL: tuple[Section, ...] = (
    section(
        "ch1",
        1,
        "DESCRIEREA ŞI SCOPUL AUDITULUI",
        None,
        "fixed",
        ("template",),
        aliases=("CAPITOLUL 1 - DESCRIEREA ȘI SCOPUL AUDITULUI",),
        has_intro_content=True,
    ),
    section("ch1.scop", 1, "Scopul auditului", "ch1", "fixed", ("template",), prototype="audit-05"),
    section("ch1.obiective", 1, "Obiective urmărite", "ch1", "fixed", ("template",)),
    section("ch1.continut", 1, "Conţinutul auditului", "ch1", "fixed", ("template",)),
    section("ch1.intocmire", 1, "Întocmirea auditului energetic", "ch1", "fixed", ("template",)),
    section("ch1.legislatie", 1, "Specificații legislative", "ch1", "fixed", ("template",)),
    section(
        "ch2",
        2,
        "DESCRIEREA ŞI ISTORICUL SOCIETĂŢII",
        None,
        "fixed",
        ("template",),
        aliases=("CAPITOLUL 2 - DESCRIEREA ȘI ISTORICUL SOCIETĂȚII",),
    ),
    section(
        "ch2.date_generale",
        2,
        "Date generale",
        "ch2",
        "data",
        ("clients", "anexa", "questionnaire"),
        facts=(AuditFact.COMPANY_NAME,),
    ),
    section(
        "ch2.manager",
        2,
        "Date privind managerul energetic al activității economice",
        "ch2",
        "data",
        ("questionnaire", "anexa"),
        prototype="audit-03",
        facts=(AuditFact.ENERGY_MANAGER,),
    ),
    section(
        "ch2.activitate",
        2,
        "Date privind activitatea desfășurată în cadrul unității economice",
        "ch2",
        "data",
        ("questionnaire",),
        prototype="audit-04",
    ),
    section(
        "ch2.localizare",
        2,
        "Localizarea companiei",
        "ch2",
        "narrative",
        ("online", "clients"),
        aliases=("Localizarea geografică și administrativă",),
    ),
    section(
        "ch2.istorie",
        2,
        "Istoria companiei",
        "ch2",
        "narrative",
        ("online", "clients"),
        aliases=("Istoricul societății",),
    ),
    section(
        "ch3",
        3,
        "DESCRIEREA SITUAŢIEI EXISTENTE",
        None,
        "narrative",
        ("dossier",),
        templates=("DESCRIEREA SITUAŢIEI EXISTENTE A {client}",),
        aliases=("CAPITOLUL 3 - DESCRIEREA SITUAȚIEI EXISTENTE",),
    ),
    section(
        "ch3.flux",
        3,
        "Descrierea fluxului tehnologic",
        "ch3",
        "narrative",
        ("dossier", "visit"),
        # Her latest audits head the overview with the process description itself (#163).
        aliases=("Descrierea fluxului tehnologic", "Descrierea procesului tehnologic"),
        templates=(
            "DESCRIEREA FLUX {process}",
            "DESCRIEREA FLUXURILOR TEHNOLOGICE {site}",
            "Descrierea procesului tehnologic {process}",
        ),
    ),
    section(
        "ch3.process",
        3,
        "Descrierea secției",
        "ch3",
        "narrative",
        ("dossier", "visit"),
        prototype="audit-01",
        templates=(
            "DESCRIEREA SECȚIEI {process}",
            "Prezentarea procesului tehnologic {process}",
            "Prezentarea fluxului tehnologic {process}",
            "{process}",
        ),
    ),
    section(
        "ch3.utilitati",
        3,
        "Situaţia existentă la nivelul alimentării cu utilități",
        "ch3",
        "narrative",
        ("dossier", "questionnaire", "visit"),
        aliases=(
            "Descrierea situației privind alimentarea cu utilități",
            "Descrierea utilităților",
            "Descrierea alimentării cu utilități",
        ),
        templates=(
            "SITUAŢIA EXISTENTĂ LA NIVELUL ALIMENTĂRII CU UTILITĂȚI A {client}",
            "DESCRIEREA SITUAȚIEI PRIVIND ASIGURAREA CU UTILITĂȚI A {client}",
            "DESCRIEREA UTILITĂȚILOR DIN CADRUL {client}",
        ),
    ),
    section(
        "ch3.apa",
        3,
        "Descrierea alimentării cu apă",
        "ch3",
        "narrative",
        ("dossier",),
        aliases=("Descrierea situației privind alimentarea cu apă",),
        templates=(
            "Descrierea situației existente la nivelul alimentării cu apă a {client}",
            "Situația existentă privind alimentarea cu apă a sediului central a {client}",
            "Alimentarea cu apă a {client}",
        ),
    ),
    section(
        "ch3.electricitate",
        3,
        "Descrierea alimentării cu energie electrică",
        "ch3",
        "narrative",
        ("dossier",),
        aliases=("Descrierea situației privind alimentarea cu energie electrică",),
        templates=(
            "Situația existentă privind alimentarea cu energie electrică a {client}",
            "Alimentarea cu energie electrică a {client}",
            "Descrierea alimentării și utilizării energiei electrice a {client}",
            "Descrierea alimentării și utilizării energie electrice a {client}",
        ),
    ),
    section(
        "ch3.gaz",
        3,
        "Descrierea alimentării cu gaz natural și energie termică",
        "ch3",
        "narrative",
        ("dossier",),
        aliases=("Descrierea situației privind alimentarea cu gaz natural și energie termică",),
        templates=(
            "Situația existentă privind alimentarea cu gaz natural a {client}",
            "Alimentarea cu gaz natural a {client}",
            "Alimentarea cu gaz natural și energie termică a {client}",
            "Situația alimentării cu gaz natural și a utilizării energiei termice "
            "în cadrul {client}",
            "Situația alimentării cu gaz natural și a utilizării energie termice "
            "în cadrul {client}",
        ),
    ),
    section(
        "ch3.carburant",
        3,
        "Descrierea alimentării carburant",
        "ch3",
        "narrative",
        ("dossier",),
        templates=("Situația existentă privind alimentarea cu carburanți a {client}",),
    ),
    section(
        "ch3.aer_comprimat",
        3,
        "Descrierea situației privind alimentarea cu aer comprimat",
        "ch3",
        "narrative",
        ("dossier",),
        prototype="audit-03",
        when=fact(AuditFact.COMPRESSED_AIR),
    ),
    section(
        "ch3.climatizare",
        3,
        "Descrierea situației privind sistemul de climatizare",
        "ch3",
        "narrative",
        ("dossier",),
        prototype="audit-03",
    ),
    section(
        "ch3.iluminat",
        3,
        "Descrierea sistemului de iluminat",
        "ch3",
        "data",
        ("questionnaire", "visit"),
        prototype="audit-03",
        aliases=(
            "Descrierea situației privind iluminarea platformei",
            "Situația sistemului de iluminat",
        ),
        templates=("Situația sistemului de iluminat din cadrul {client}",),
    ),
    section(
        "ch3.parc_auto",
        3,
        "Descrierea situației privind parcul auto",
        "ch3",
        "data",
        ("questionnaire",),
        prototype="audit-05",
        when=fact(AuditFact.FLEET),
        aliases=("Situația parcului auto",),
        templates=(
            "Situația parcului auto din cadrul {client}",
            "Situația parcului auto în cadrul {client}",
        ),
    ),
    section(
        "ch3.contorizare",
        3,
        "Situaţia contorizării consumatorilor de energie",
        "ch3",
        "data",
        ("questionnaire", "visit"),
        aliases=(
            "SITUAŢIA EXISTENTĂ PRIVIND CONTORIZAREA",
            "Situația contorizării consumurilor de energie",
        ),
        templates=(
            "SITUAŢIA CONTORIZĂRII CONSUMATORILOR DE ENERGIE DIN CADRUL {client}",
            # One heading in her latest audits for metering and automation together (#163).
            "SITUAŢIA CONTORIZĂRII ȘI AUTOMATIZĂRII CONSUMATORILOR DE ENERGIE DIN CADRUL {client}",
        ),
    ),
    section(
        "ch3.automatizare",
        3,
        "Situaţia automatizărilor",
        "ch3",
        "data",
        ("questionnaire", "visit"),
        aliases=("SITUAŢIA EXISTENTĂ PRIVIND AUTOMATIZAREA",),
        templates=("SITUAŢIA AUTOMATIZĂRILOR DIN CADRUL {client}",),
    ),
    section(
        "ch3.consumatori",
        3,
        "Principalii consumatori de energie electrică",
        "ch3",
        "data",
        ("dossier",),
        prototype="audit-03",
    ),
    section(
        "ch3.equipment",
        3,
        "Echipamentele și utilajele utilizate pentru manipulare, ambalare și depozitare",
        "ch3.flux",
        "data",
        ("dossier",),
    ),
)
