"""Catalogue entries for analysis, measurements, measures and financing."""

from ema.audit.catalogue_types import Condition, MaterialKind, Section, material, section

ANALYSIS: tuple[Section, ...] = (
    section(
        "ch4",
        4,
        "Analiza modului în care se realizează consumurile energetice pe platforma societății",
        None,
        "data_blocks",
        ("consumption_analysis",),
        aliases=("ANALIZA CONSUMURILOR ENERGETICE ANUALE",),
        templates=(
            "Analiza modului în care se realizează consumurile energetice în cadrul {client}",
        ),
    ),
    section(
        "ch4.productie", 4, "Analiza producției", "ch4", "data_blocks", ("consumption_analysis",)
    ),
    section(
        "ch4.consum",
        4,
        "Analiza consumului de energie și de apă",
        "ch4",
        "data_blocks",
        ("consumption_analysis",),
        aliases=("ANALIZA CONSUMULUI DE ENERGIE",),
    ),
    section(
        "ch4.electricitate",
        4,
        "Analiza consumului de energie electrică",
        "ch4.consum",
        "data_blocks",
        ("consumption_analysis",),
        templates=("Analiza consumului de energie electrică din {source}",),
    ),
    section(
        "ch4.electricitate_pv",
        4,
        "Analiza consumului de energie electrică parcul fotovoltaic propriu",
        "ch4.consum",
        "data_blocks",
        ("consumption_analysis",),
        prototype="piee_model_2026",
    ),
    section(
        "ch4.gaz",
        4,
        "Analiza consumului de gaz natural",
        "ch4.consum",
        "data_blocks",
        ("consumption_analysis",),
        aliases=("Analiza consumului de gaze naturale",),
    ),
    section(
        "ch4.carburant",
        4,
        "Analiza consumului de carburanți",
        "ch4.consum",
        "data_blocks",
        ("consumption_analysis",),
        aliases=("Analiza consumului de carburant", "Analiza consumului de motorină"),
    ),
    section(
        "ch4.apa",
        4,
        "Analiza consumului de apă",
        "ch4.consum",
        "data_blocks",
        ("consumption_analysis",),
        templates=("Analiza consumului de apă {water_kind}",),
    ),
    section(
        "ch4.echivalent",
        4,
        "Analiza consumului echivalent de energie",
        "ch4",
        "data_blocks",
        ("consumption_analysis",),
    ),
    section(
        "ch4.echiv_electric",
        4,
        "Analiza consumului total echivalent de energie electrică din SEN",
        "ch4.echivalent",
        "data_blocks",
        ("consumption_analysis",),
        aliases=(
            "Analiza consumului echivalent de energie electrică",
            "Analiza consumului total echivalent de energie electrică",
        ),
    ),
    section(
        "ch4.echiv_pv",
        4,
        "Analiza consumului echivalent de energie electrică fotovoltaică",
        "ch4.echivalent",
        "data_blocks",
        ("consumption_analysis",),
        prototype="piee_model_2026",
    ),
    section(
        "ch4.echiv_gaz",
        4,
        "Analiza consumului total echivalent de gaz natural",
        "ch4.echivalent",
        "data_blocks",
        ("consumption_analysis",),
        aliases=("Analiza consumului echivalent de gaz natural",),
    ),
    section(
        "ch4.echiv_carburant",
        4,
        "Analiza consumului total echivalent de carburant",
        "ch4.echivalent",
        "data_blocks",
        ("consumption_analysis",),
        aliases=("Analiza consumului echivalent de carburant",),
    ),
    section(
        "ch4.echiv_total",
        4,
        "Analiza consumului total echivalent de energie",
        "ch4.echivalent",
        "data_blocks",
        ("consumption_analysis",),
    ),
    section(
        "ch4.concluzii",
        4,
        "Concluziile privind analiza consumului echivalent de energie",
        "ch4",
        "narrative",
        ("consumption_analysis",),
    ),
    section(
        "ch4.eficienta",
        4,
        "Analiza eficienței utilizării energiei",
        "ch4",
        "data_blocks",
        ("consumption_analysis",),
        aliases=("analiza eficienței utilizării energie",),
    ),
    section(
        "ch4.specific_electric",
        4,
        "Analiza consumului specific echivalent de energie electrică",
        "ch4.eficienta",
        "data_blocks",
        ("consumption_analysis",),
        aliases=("Analiza consumului specific echivalent total de energie electrică",),
    ),
    section(
        "ch4.specific_pv",
        4,
        "Analiza consumului specific echivalent de energie electrică fotovoltaică",
        "ch4.eficienta",
        "data_blocks",
        ("consumption_analysis",),
        prototype="piee_model_2026",
    ),
    section(
        "ch4.specific_gaz",
        4,
        "Analiza consumului specific echivalent de gaz natural",
        "ch4.eficienta",
        "data_blocks",
        ("consumption_analysis",),
    ),
    section(
        "ch4.specific_carburant",
        4,
        "Analiza consumului specific echivalent de carburant",
        "ch4.eficienta",
        "data_blocks",
        ("consumption_analysis",),
    ),
    section(
        "ch4.specific_total",
        4,
        "Analiza consumului specific echivalent de energie totală",
        "ch4.eficienta",
        "data_blocks",
        ("consumption_analysis",),
    ),
    section(
        "ch4.specific_apa",
        4,
        "Analiza consumului specific echivalent de apă",
        "ch4.eficienta",
        "data_blocks",
        ("consumption_analysis",),
        aliases=("Analiza consumului specific de apă potabilă",),
        templates=("Analiza consumului specific echivalent de apă {water_kind}",),
    ),
    section(
        "ch4.intensitate",
        4,
        "Analiza intensității energetice",
        "ch4",
        "data_blocks",
        ("consumption_analysis",),
        aliases=("Intensitatea energetică",),
    ),
    section(
        "ch4.mediu",
        4,
        "Analiza impactului de mediu",
        "ch4",
        "data_blocks",
        ("consumption_analysis",),
        aliases=("Impactul de mediu al utilizării energiei",),
    ),
    section(
        "ch4.bilant_real",
        4,
        "Analiza bilanțului energetic real",
        "ch4",
        "data_blocks",
        ("consumption_analysis",),
        aliases=("Bilanțul energetic real",),
        prototype="AUDIT-02",
    ),
    section(
        "ch5",
        5,
        "BILANȚURILE ENERGETICE",
        None,
        "measurements",
        ("measurements",),
        prototype="AUDIT-03",
        when=Condition(
            "any", children=(material(MaterialKind.METER), material(MaterialKind.THERMAL))
        ),
    ),
    section(
        "ch5.electric",
        5,
        "Bilanţul electroenergetic și descrierea echipamentelor utilizate pentru măsurători",
        "ch5",
        "measurements",
        ("measurements",),
        prototype="AUDIT-03",
        when=material(MaterialKind.METER),
    ),
    section(
        "ch5.electric_fisa",
        5,
        "Fișa de măsurători electroenergetice",
        "ch5",
        "measurements",
        ("measurements",),
        prototype="AUDIT-03",
        when=material(MaterialKind.METER),
    ),
    section(
        "ch5.electric_rezultate",
        5,
        "Rezultatele măsurătorilor electroenergetice",
        "ch5",
        "measurements",
        ("measurements",),
        prototype="AUDIT-03",
        when=material(MaterialKind.METER),
    ),
    section(
        "ch5.electric_concluzii",
        5,
        "Concluziile obținute în urma măsurătorilor electroenergetice",
        "ch5",
        "measurements",
        ("measurements",),
        prototype="AUDIT-03",
        when=material(MaterialKind.METER),
    ),
    section(
        "ch5.termic",
        5,
        "Bilanţul termic și descrierea echipamentelor utilizate pentru măsurători",
        "ch5",
        "measurements",
        ("measurements",),
        prototype="AUDIT-03",
        when=material(MaterialKind.THERMAL),
    ),
    section(
        "ch5.termic_fisa",
        5,
        "Fișa de măsurători termoenergetice",
        "ch5",
        "measurements",
        ("measurements",),
        prototype="AUDIT-03",
        when=material(MaterialKind.THERMAL),
    ),
    section(
        "ch5.termic_rezultate",
        5,
        "Rezultatele măsurătorilor termoenergetice",
        "ch5",
        "measurements",
        ("measurements",),
        prototype="AUDIT-03",
        when=material(MaterialKind.THERMAL),
    ),
    section(
        "ch6",
        6,
        "MĂSURI DE CREȘTERE A EFICIENŢEI ENERGETICE",
        None,
        "narrative",
        ("auditor",),
        aliases=("MĂSURI PROPUSE PENTRU CREȘTEREA EFICIENȚEI ENERGETICE",),
        templates=("MĂSURI DE CREȘTERE A EFICIENŢEI ENERGETICE {period}",),
    ),
    section(
        "ch6.indicatori",
        6,
        "Indicatori de performanță financiară",
        "ch6",
        "calc",
        ("template", "calculation"),
    ),
    section(
        "ch6.generale",
        6,
        "Măsuri generale de organizare pentru creşterea eficienţei energetice",
        "ch6",
        "fixed",
        ("template",),
        aliases=("Măsuri generale pentru creșterea eficienței energetice",),
    ),
    section(
        "ch6.specifice",
        6,
        "Măsuri specifice pentru creşterea eficienţei energetice",
        "ch6",
        "narrative",
        ("auditor", "calculation"),
        aliases=("Măsuri specifice pentru creșterea eficienței energetice",),
    ),
    section(
        "ch6.measure",
        6,
        "{measure}",
        "ch6.specifice",
        "calc",
        ("auditor", "calculation"),
        templates=("{measure}",),
    ),
    section(
        "ch6.sinteza",
        6,
        "Sinteza măsurilor de eficiență energetică propuse pentru implementare",
        "ch6",
        "calc",
        ("auditor", "calculation"),
        aliases=("Sinteza măsurilor de eficientă energetică propuse",),
    ),
    section(
        "ch7",
        7,
        "SURSE DE FINANȚARE",
        None,
        "fixed",
        ("template",),
        aliases=("CAPITOLUL 7 - SURSE DE FINANȚARE",),
    ),
)
