"""Generate the S16 contract and an operation-level diff from frozen S16a."""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
from typing import Any

from ema.api import create_app
from ema.core.workspace import Workspace

ROOT = Path(__file__).resolve().parents[1]
BASELINE = ROOT / "openapi/ema.v1.s16a.json"
CURRENT = ROOT / "openapi/ema.v1.json"
DIFF = ROOT / "openapi/s16-diff.md"
METHODS = {"get", "post", "put", "patch", "delete"}


def operations(schema: dict[str, Any]) -> dict[tuple[str, str], dict[str, Any]]:
    return {
        (method.upper(), path): operation
        for path, methods in schema["paths"].items()
        for method, operation in methods.items()
        if method in METHODS
    }


def media(operation: dict[str, Any], key: str) -> str:
    body = operation.get(key, {})
    return ", ".join(sorted(body.get("content", {}))) or "—"


def generate() -> None:  # noqa: C901
    baseline = json.loads(BASELINE.read_text(encoding="utf-8"))
    with tempfile.TemporaryDirectory() as directory:
        current = create_app(Workspace(Path(directory)), 8766).openapi()
    CURRENT.write_text(
        json.dumps(current, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    old, new = operations(baseline), operations(current)
    lines = ["# S16 OpenAPI diff", "", "Generated by `scripts/generate_openapi_s16.py`.", ""]
    lines += ["## Added and removed operations", ""]
    for label, changed in (
        ("Added", new.keys() - old.keys()),
        ("Removed", old.keys() - new.keys()),
    ):
        lines.append(f"### {label}")
        lines.append("")
        source = new if label == "Added" else old
        lines += [
            f"- `{method} {path}` — `{source[(method, path)]['operationId']}`"
            for method, path in sorted(changed)
        ] or ["- None"]
        lines.append("")
    lines += [
        "## Changed operations",
        "",
        "| Method and path | Operation ID | Request media | Response statuses | `x-provisional` |",
        "|---|---|---|---|---|",
    ]
    for method, path in sorted(old.keys() & new.keys()):
        before, after = old[(method, path)], new[(method, path)]
        if before == after:
            continue
        request = f"{media(before, 'requestBody')} → {media(after, 'requestBody')}"
        statuses = (
            f"{','.join(sorted(before['responses']))} → {','.join(sorted(after['responses']))}"
        )
        provisional = f"{before.get('x-provisional', '—')} → {after.get('x-provisional', '—')}"
        lines.append(
            f"| `{method} {path}` | `{before['operationId']}` → `{after['operationId']}` "
            f"| {request} | {statuses} | {provisional} |"
        )
    lines += ["", "## Schemas", ""]
    old_schemas = baseline["components"]["schemas"]
    new_schemas = current["components"]["schemas"]
    for label, names in (
        ("Added", new_schemas.keys() - old_schemas.keys()),
        ("Removed", old_schemas.keys() - new_schemas.keys()),
        (
            "Changed",
            {
                name
                for name in old_schemas.keys() & new_schemas.keys()
                if old_schemas[name] != new_schemas[name]
            },
        ),
    ):
        lines.append(f"- {label}: " + (", ".join(f"`{name}`" for name in sorted(names)) or "none"))
    lines += ["", "### Changed (additive)", ""]
    for name in sorted(old_schemas.keys() & new_schemas.keys()):
        before = old_schemas[name]
        after = new_schemas[name]
        added = set(after.get("properties", {})) - set(before.get("properties", {}))
        if added and set(before.get("properties", {})) <= set(after.get("properties", {})):
            lines.append(f"- `{name}`: " + ", ".join(f"`{field}`" for field in sorted(added)))
    lines += ["", "## Error status changes", ""]
    for key in sorted(old.keys() & new.keys()):
        before, after = old[key]["responses"], new[key]["responses"]
        old_errors = {code for code in before if int(code) >= 400}
        new_errors = {code for code in after if int(code) >= 400}
        added = new_errors - old_errors
        removed = old_errors - new_errors
        if added or removed:
            names = ", ".join(
                f"{code} ({after[code].get('description', '')})" for code in sorted(added)
            )
            lines.append(
                f"- `{key[0]} {key[1]}`: added {names or 'none'}; "
                f"removed {', '.join(sorted(removed)) or 'none'}"
            )
    lines += ["", "## Response media changes", ""]
    for key in sorted(old.keys() & new.keys()):
        before, after = old[key]["responses"], new[key]["responses"]
        old_media = {status: sorted(value.get("content", {})) for status, value in before.items()}
        new_media = {status: sorted(value.get("content", {})) for status, value in after.items()}
        if old_media != new_media:
            lines.append(f"- `{key[0]} {key[1]}`: `{old_media}` → `{new_media}`")
    DIFF.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    generate()
